// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKpu2Gr-nxpJNt_4eOm6crp36_HgtLIQo',
    appId: '1:868783385410:web:10b99987b8fb4df200b6db',
    messagingSenderId: '868783385410',
    projectId: 'sway-868c2',
    authDomain: 'sway-868c2.firebaseapp.com',
    storageBucket: 'sway-868c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYDJotr-MY85HlBl5Cf_Gj8-urbR5emzk',
    appId: '1:868783385410:android:12b82860a9bfccd200b6db',
    messagingSenderId: '868783385410',
    projectId: 'sway-868c2',
    storageBucket: 'sway-868c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgsjvJkSb_cKGrOZe6aGli7tDJv_1bZQ',
    appId: '1:868783385410:ios:66c5646a34b18c3700b6db',
    messagingSenderId: '868783385410',
    projectId: 'sway-868c2',
    storageBucket: 'sway-868c2.appspot.com',
    iosClientId: '868783385410-j8tvhpp70qjf0rk29m667ouvptb473p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgsjvJkSb_cKGrOZe6aGli7tDJv_1bZQ',
    appId: '1:868783385410:ios:66c5646a34b18c3700b6db',
    messagingSenderId: '868783385410',
    projectId: 'sway-868c2',
    storageBucket: 'sway-868c2.appspot.com',
    iosClientId: '868783385410-j8tvhpp70qjf0rk29m667ouvptb473p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKpu2Gr-nxpJNt_4eOm6crp36_HgtLIQo',
    appId: '1:868783385410:web:0dbef17eb95227cd00b6db',
    messagingSenderId: '868783385410',
    projectId: 'sway-868c2',
    authDomain: 'sway-868c2.firebaseapp.com',
    storageBucket: 'sway-868c2.appspot.com',
  );
}
